function contourcreator2(xdata1, ydata1, zdata1)
%CREATEFIGURE(XDATA1,YDATA1,ZDATA1)
%  XDATA1:  contour x
%  YDATA1:  contour y
%  ZDATA1:  contour z

%  Auto-generated by MATLAB on 23-Jun-2014 19:43:17

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'Layer','top','FontSize',14,...
    'FontName','Arial');
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 87.1875]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 1000]);
box(axes1,'on');
hold(axes1,'all');

% Create contour
contour(xdata1,ydata1,zdata1,'LineWidth',0.1,'LineColor',[0 0 0],...
    'LevelStep',1,...
    'Fill','on',...
    'Parent',axes1);

% Create title
title('%R for Hard Interface Into Waveguide, from n=1 to n=2',...
    'FontSize',20,...
    'FontName','Arial');

% Create xlabel
xlabel('Wavelength (nm)','FontSize',16,'FontName','Arial');

% Create ylabel
ylabel('Angle of Incidence, (deg)','FontSize',16,'FontName','Arial');

% Create zlabel
zlabel('Average %R in AM1.5','Visible','off');

% Create colorbar
colorbar('peer',axes1,'FontSize',14,'FontName','Arial');

